easy_admin:
    site_name: '[zeDisplay]'
    design:
        menu:
            - { label: 'Dashboard', route: 'dashboard', icon: 'dashboard', default: true }
            - { entity: 'User', icon: 'user', permission:  [ROLE_SUPER_ADMIN]}
            - { entity: 'Client', icon: 'user-o', permission: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
            - { entity: 'GroupCompany', icon: 'circle' , permission: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
            - { entity: 'Establishment', icon: 'building', permission:  [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
            - { entity: 'Device', icon: 'tv', permission: [ROLE_ADMIN, ROLE_SUPER_ADMIN, ROLE_USER]}
            - { entity: 'Channel', icon: 'book', permission: [ROLE_ADMIN, ROLE_SUPER_ADMIN, ROLE_USER] }
            - { entity: 'Content', icon: 'book', permission: [ROLE_ADMIN, ROLE_SUPER_ADMIN, ROLE_USER] }

        assets:
            favicon: '/build/images/favicon.png'
            js:
                # By default, EasyAdminBundle embeds a limited version of Bootstrap JS.
                # For collapsible form filters to work, a full version should be added:
                - 'bundles/easyadmin/bootstrap-all.js'
            css:
                - 'bundles/easyadmin/bootstrap-all.css'
        brand_color: '#79cc42'
    list:
        actions:
            - { name: 'show', icon: 'search', label: '' }
            - { name: 'edit', icon: 'pencil', label: '' }
            - { name: 'delete', icon: 'trash', label: '' }
    entities:
        # List the entity class name you want to manage
        User:
            class: App\Entity\User
            role: [ROLE_ADMIN, ROLE_SUPER_ADMIN]
#            templates:
#                list: 'admin/post/list.html.twig'
            list:
#                form_filters:
#                    - { property: client, label: 'Client' }
                fields:
                    - fullname
                    - client
                    - username
                    - email
                    - { property: 'enabled', permission: ROLE_SUPER_ADMIN }
                    - created
            show:
                fields:
                    - fullname
                    - username
                    - email
                    - created
                    - updated
                    - lastLogin
                    - roles
            form:
                fields:
                    - fullname
                    - username
                    - email
                    - { property: 'enabled', permission: ROLE_SUPER_ADMIN }
                    - client
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ADMINISTRADOR': 'ROLE_ADMIN', 'USUARIO BASICO': 'ROLE_USER' } } }
            delete:
                role: [ROLE_ADMIN, ROLE_SUPER_ADMIN]

        Client:
            class: App\Entity\Client
            role: [ROLE_ADMIN, ROLE_SUPER_ADMIN]
            list:
                fields:
                    - id
                    - name
                    - companyName
                    - city

            new:
                role: ROLE_SUPER_ADMIN
                fields:
                    - name
                    - companyName
                    - address
                    - city
                    - postalCode
                    - contactPersonPhone
            edit:
                role: [ROLE_ADMIN, ROLE_SUPER_ADMIN]
                fields:
                    - name
                    - companyName
                    - address
                    - city
                    - postalCode
                    - contactPersonPhone
            delete:
                role: ROLE_SUPER_ADMIN

        GroupCompany:
            class: App\Entity\GroupCompany
            list:
                fields:
                    - name

            form:
                role: [ROLE_ADMIN, ROLE_SUPER_ADMIN]
                fields:
                    - name
            delete:
                role:  [ROLE_ADMIN, ROLE_SUPER_ADMIN]

        Establishment:
            class: App\Entity\Establishment
            list:
                fields:
                    - groupCompany
                    - name
            show:
                fields:
                    - groupCompany
                    - name
            form:
                role: [ROLE_ADMIN, ROLE_SUPER_ADMIN]
                fields:
                    - groupCompany
                    - name
            delete:
                role:  [ROLE_ADMIN, ROLE_SUPER_ADMIN]

        Device:
            class: App\Entity\Device
            list:
                fields:
                    - id
                    - establishment
                    - name
                    - channels
            show:
                fields:
                    - id
                    - establishment
                    - name
                    - channels
            new:
                role: [ROLE_ADMIN, ROLE_SUPER_ADMIN]
                fields:
                    - establishment
                    - name
                    - channels
            edit:
                role: [ROLE_ADMIN, ROLE_SUPER_ADMIN, ROLE_USER]
                fields:
                    - establishment
                    - name
                    - channels
            delete:
                role: [ROLE_ADMIN, ROLE_SUPER_ADMIN]

        Channel:
            class: App\Entity\Channel
            list:
                fields:
                    - name
                    - contents
            show:
                fields:
                    - name
                    - contents

            form:
                fields:
                    - name

        Content:
            class: App\Entity\Content
            list:
                fields:
                    - name
                    - type
                    - url
            show:
                fields:
                    - name
                    - type
                    - url

            form:
                fields:
                    - name
                    - { property: 'type', type: 'choice', type_options: { multiple: false, choices: { 'VIDEO': 'video', 'IMG': 'IMG' } } }
                    - url
