easy_admin_bundle:
    resource: 'App\Controller\EasyAdmin\AdminController'
    prefix: /{_locale}/backend
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'
    type: annotation
